spring:
  application:
    name: lms

  datasource:
    url: jdbc:mariadb://localhost:3306/spring_study
    driver-class-name: org.mariadb.jdbc.Driver
    username: hj
    password: zerobase

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

