spring:
  application:
    name: lms

  datasource:
    url: jdbc:mariadb://localhost:3306/spring_study
    driver-class-name: org.mariadb.jdbc.Driver
    username: hj
    password: zerobase

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: applicationPrivate.yml

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
